### ISSUE TITLE
403 Error with downloading Training dataset files

### ISSUE THREAD

**Issue by yashbhalgat** [OpenSun3D/OpenSun3D.github.io#4]
I am trying to download the dataset, but facing the following error with `wide.zip` and `wide_intrinsics.zip` files for _almost_ every other scene:
```
Error downloading https://docs-assets.developer.apple.com/ml-research/datasets/arkitscenes/v1/raw/Training/40777069/wide.zip, error: Command 'curl https://docs-assets.developer.apple.com/ml-
research/datasets/arkitscenes/v1/raw/Training/40777069/wide.zip -o /work/yashsb/datasets/ARKitScenes/FullTrainingSet/40777069/wide.zip.tmp --fail' returned non-zero exit status 22.
Downloading file /work/yashsb/datasets/ARKitScenes/FullTrainingSet/40777069/wide_intrinsics.zip 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403
Error downloading https://docs-assets.developer.apple.com/ml-research/datasets/arkitscenes/v1/raw/Training/40777069/wide_intrinsics.zip, error: Command 'curl https://docs-assets.developer.ap
ple.com/ml-research/datasets/arkitscenes/v1/raw/Training/40777069/wide_intrinsics.zip -o /work/yashsb/datasets/ARKitScenes/FullTrainingSet/40777069/wide_intrinsics.zip.tmp --fail' returned n
on-zero exit status 22.
```

I am seeing this with scenes from both ChallengeDevelopmentSet and FullTrainingSet.

Thanks,
Yash

**Comment by aycatakmaz** [comment]
Hi @yashbhalgat 

Thanks for bringing this to our attention!

The original ARKitScenes dataset has different assets available for different tasks (two main tasks are 3DOD and depth-upsampling). The `wide` and `wide_intrinsics` assets are available for download only for scenes which are originally used for the depth-upsampling task as mentioned [here](https://github.com/apple/ARKitScenes/pull/43#pullrequestreview-1139111841). The training list we added in our repo includes **all** training scenes with raw data - so some of the scenes indeed do not have `wide` and `wide_intrinsics` assets, as you observed. We nevertheless added `wide` and `wide_intrinsics` assets in the the challenge data download script, prompting the script to download them if they are available for any given scene. 

If you will not be using `wide` and `wide_intrinsics` (or any other specific asset), you can simply remove them from the [list of assets to be downloaded](https://github.com/OpenSun3D/OpenSun3D.github.io/blob/0f8c82e0c52652ff44560df2b69172e5460027ea/challenge/download_data_opensun3d.py#L174-176) in the challenge data download script. 


Alternatively, in case you only want to download the training scenes that indeed have `wide`assets, we have just added a list of such training scenes [here](https://github.com/OpenSun3D/OpenSun3D.github.io/blob/main/challenge/benchmark_file_lists/full_training_scenes_w_wide_assets.csv). In order to download that training subset, you can use the following command:

```
python3 challenge/download_data_opensun3d.py --data_type=full_training_set_w_wide_assets --download_dir PATH/TO/ARKITSCENES/DOWNLOAD/DIR
```

Hope this helps!

Best,
Ayca

**Comment by yashbhalgat** [comment]
That's helpful, thank you. :)
